<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260821000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create mapping, sync run, sync error, and webhook event tables.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE product_mapping (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, odoo_template_id INT NOT NULL, odoo_variant_id INT DEFAULT NULL, woo_product_id INT NOT NULL, sku VARCHAR(191) DEFAULT NULL, sync_status VARCHAR(255) NOT NULL, source_hash VARCHAR(64) DEFAULT NULL, last_synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_error TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_product_odoo_template ON product_mapping (odoo_template_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_product_woo ON product_mapping (woo_product_id)');
        $this->addSql('CREATE TABLE category_mapping (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, odoo_category_id INT NOT NULL, woo_category_id INT NOT NULL, odoo_parent_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, source_hash VARCHAR(64) DEFAULT NULL, last_synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_category_odoo ON category_mapping (odoo_category_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_category_woo ON category_mapping (woo_category_id)');
        $this->addSql('CREATE TABLE brand_mapping (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, odoo_attribute_id INT NOT NULL, odoo_value_id INT NOT NULL, woo_brand_id INT NOT NULL, name VARCHAR(255) NOT NULL, normalized_name VARCHAR(255) NOT NULL, last_synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_brand_odoo_value ON brand_mapping (odoo_value_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_brand_woo ON brand_mapping (woo_brand_id)');
        $this->addSql('CREATE TABLE order_mapping (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, woo_order_id INT NOT NULL, odoo_sale_order_id INT DEFAULT NULL, idempotency_key VARCHAR(191) NOT NULL, sync_status VARCHAR(255) NOT NULL, last_synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_error TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_order_woo ON order_mapping (woo_order_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_order_idempotency ON order_mapping (idempotency_key)');
        $this->addSql('CREATE TABLE sync_run (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sync_type VARCHAR(255) NOT NULL, direction VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, processed_count INT NOT NULL, created_count INT NOT NULL, updated_count INT NOT NULL, skipped_count INT NOT NULL, error_count INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE sync_error (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sync_run_id INT NOT NULL, entity_type VARCHAR(100) NOT NULL, external_id VARCHAR(191) NOT NULL, error_code VARCHAR(100) DEFAULT NULL, message TEXT NOT NULL, retry_count INT NOT NULL, resolved BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_SYNC_ERROR_RUN ON sync_error (sync_run_id)');
        $this->addSql('CREATE INDEX idx_sync_error_unresolved ON sync_error (resolved)');
        $this->addSql('ALTER TABLE sync_error ADD CONSTRAINT FK_SYNC_ERROR_RUN FOREIGN KEY (sync_run_id) REFERENCES sync_run (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE TABLE webhook_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider VARCHAR(50) NOT NULL, external_event_id VARCHAR(191) DEFAULT NULL, entity_id VARCHAR(191) DEFAULT NULL, event_type VARCHAR(100) NOT NULL, payload_hash VARCHAR(64) NOT NULL, status VARCHAR(255) NOT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_webhook_lookup ON webhook_event (provider, external_event_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_webhook_payload ON webhook_event (provider, payload_hash)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE sync_error');
        $this->addSql('DROP TABLE sync_run');
        $this->addSql('DROP TABLE webhook_event');
        $this->addSql('DROP TABLE order_mapping');
        $this->addSql('DROP TABLE brand_mapping');
        $this->addSql('DROP TABLE category_mapping');
        $this->addSql('DROP TABLE product_mapping');
    }
}
