parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/Mapping/Entity/'
            - '../src/Sync/Entity/'

    App\Odoo\Client\OdooClientInterface: '@App\Odoo\Client\OdooJsonRpcClient'

    App\Odoo\Client\OdooJsonRpcClient:
        arguments:
            $baseUrl: '%env(ODOO_URL)%'
            $database: '%env(ODOO_DATABASE)%'
            $username: '%env(ODOO_USERNAME)%'
            $apiKey: '%env(ODOO_API_KEY)%'
            $timeout: '%env(float:ODOO_TIMEOUT)%'
